services:
  db:
    image: postgres:16-alpine
    container_name: justcook-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: esv190997
      POSTGRES_DB: justcook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
